- name: Ensure server's default ip and hostname are in /etc/hosts
  lineinfile: >
    dest=/etc/hosts
    line="{{ ansible_default_ipv4.address }} {{ ansible_fqdn }} {{ ansible_hostname }}"
    regexp="^{{ ansible_default_ipv4.address }}"
    state=present
