- name: Install Samba
  package: name={{ item }} state=present
  with_items: '{{ authad_samba_packages }}'
  tags: install_package

- name: Configure Samba as a domain member
  template:
    src: smb.conf.j2
    dest: /etc/samba/smb.conf
    owner: root
    group: root
    mode: 644
  notify: restart samba


- name: Ensure Samba is started and enabled on boot
  service:
    name: '{{ smb_service_name }}'
    state: started
    enabled: yes
