---
- name: Install Kerberos and LDAP clients
  package: name={{ item }} state=present
  with_items: '{{ authad_kerb_packages }}'
  tags: install_package

- name: Configure Kerberos integration with AD
  template:
    src: krb5.conf.j2
    dest: /etc/krb5.conf
    owner: root
    group: root
    mode: 644


# - name: Get kerberos ticket with the sambe keytab
#   command: kinit -k -t /etc/krb5.keytab {{ ansible_hostname | upper }}$\@{{ adauth_realm }}
#   args:
#     creates: /tmp/krb5cc_0
